# Generated by Django 4.2.10 on 2026-02-17 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_number_hash', models.CharField(db_index=True, help_text='SHA-256 hash of caller number. Plaintext never stored.', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='active', max_length=20)),
                ('initial_risk_score', models.IntegerField(default=0, help_text='Risk score from pre-call DB lookup.')),
                ('current_risk_score', models.IntegerField(default=0, help_text='Most recent ML model risk score.')),
                ('peak_risk_score', models.IntegerField(default=0, help_text='Highest risk score recorded during the call.')),
                ('final_risk_score', models.IntegerField(default=0, help_text='Risk score at the moment the call ended.')),
                ('ml_confidence', models.FloatField(default=0.0, help_text='ML model confidence at end of session (0.0–1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('alert_triggered', models.BooleanField(default=False, help_text='Whether a scam alert overlay was shown to the user.')),
                ('alert_count', models.IntegerField(default=0, help_text='Number of alerts shown during the call.')),
                ('alert_threshold', models.IntegerField(default=70, help_text='Risk score at which an alert is triggered.')),
                ('call_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('chunks_processed', models.IntegerField(default=0, help_text='Number of transcript chunks analyzed by the ML model.')),
                ('user_confirmed_scam', models.BooleanField(blank=True, help_text='True=scam, False=not scam, None=no feedback given.', null=True)),
                ('user_feedback_notes', models.TextField(blank=True)),
                ('detected_patterns', models.JSONField(default=list, help_text='Scam pattern labels returned by the ML model.')),
                ('detected_scam_type', models.CharField(blank=True, max_length=50)),
                ('content_deleted', models.BooleanField(default=False, help_text='True once all transcript chunks have been deleted.')),
                ('content_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, choices=[('non_scam', 'Not a scam – deleted immediately'), ('no_consent', 'Scam confirmed but no storage consent given'), ('user_request', 'User explicitly requested deletion'), ('auto_expired', 'Auto-expired after 90 days'), ('session_end', 'Session ended without user confirmation')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Session',
                'verbose_name_plural': 'Call Sessions',
                'db_table': 'call_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('ml_detection', 'ML Model Detection'), ('pattern_detected', 'Scam Pattern Detected'), ('high_risk_threshold', 'High Risk Threshold Crossed'), ('combined_detection', 'Combined Signal Detection')], max_length=30)),
                ('risk_score_at_alert', models.IntegerField()),
                ('confidence_at_alert', models.FloatField(default=0.0)),
                ('trigger_patterns', models.JSONField(default=list)),
                ('detected_scam_type', models.CharField(blank=True, max_length=50)),
                ('alert_message', models.TextField()),
                ('user_dismissed', models.BooleanField(default=False)),
                ('user_ended_call', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='real_time_detection.callsession')),
            ],
            options={
                'verbose_name': 'Risk Alert',
                'verbose_name_plural': 'Risk Alerts',
                'db_table': 'risk_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmedScamConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_number_hash', models.CharField(db_index=True, max_length=64)),
                ('full_transcript', models.TextField(help_text='Full conversation with PII redacted.')),
                ('final_risk_score', models.IntegerField(default=0)),
                ('final_scam_type', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('all_patterns_detected', models.JSONField(default=list)),
                ('pii_redacted', models.BooleanField(default=False)),
                ('voice_anonymized', models.BooleanField(default=False)),
                ('user_consented_storage', models.BooleanField(default=False)),
                ('user_consented_training', models.BooleanField(default=False)),
                ('used_for_training', models.BooleanField(default=False)),
                ('training_used_at', models.DateTimeField(blank=True, null=True)),
                ('auto_delete_at', models.DateTimeField(help_text='Hard deletion deadline. Set to now + 90 days automatically.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_scam_conversation', to='real_time_detection.callsession')),
            ],
            options={
                'verbose_name': 'Confirmed Scam Conversation',
                'verbose_name_plural': 'Confirmed Scam Conversations',
                'db_table': 'confirmed_scam_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_number', models.IntegerField(help_text='Sequential position (1, 2, 3 …)')),
                ('transcript_text', models.TextField(help_text='Transcribed text. TEMPORARY.')),
                ('speaker', models.CharField(choices=[('user', 'App User'), ('caller', 'Caller'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('chunk_risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ml_analyzed', models.BooleanField(default=False)),
                ('ml_confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('timestamp', models.DateTimeField(help_text='When chunk was captured on device.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='real_time_detection.callsession')),
            ],
            options={
                'verbose_name': 'Transcript Chunk (Temporary)',
                'verbose_name_plural': 'Transcript Chunks (Temporary)',
                'db_table': 'transcript_chunks',
                'ordering': ['session', 'chunk_number'],
                'indexes': [models.Index(fields=['session', 'chunk_number'], name='transcript__session_2a8059_idx')],
                'unique_together': {('session', 'chunk_number')},
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['user', '-started_at'], name='call_sessio_user_id_ff0280_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status'], name='call_sessio_status_eae999_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['content_deleted'], name='call_sessio_content_b5f57d_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller_number_hash'], name='call_sessio_caller__ce7cfe_idx'),
        ),
    ]
