# Generated by Django 4.2.10 on 2026-02-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='auto_report_recommended',
            field=models.BooleanField(default=False, help_text='True if risk score reached threshold for auto-reporting (≥70).'),
        ),
    ]
