# Generated by Django 4.2.10 on 2026-03-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_detection', '0002_callsession_auto_report_recommended'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcriptchunk',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transcriptchunk',
            name='session',
        ),
        migrations.AddField(
            model_name='callsession',
            name='full_transcript',
            field=models.TextField(blank=True, help_text='Cumulative transcript built from all chunks. TEMPORARY - deleted post-call.'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='scam_detected_by_ai',
            field=models.BooleanField(default=False, help_text='True if AI determined peak_risk >= 70%. AI decision, not user.'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='user_consented_storage',
            field=models.BooleanField(default=False, help_text='Did user consent to store conversation for training?'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='chunks_processed',
            field=models.IntegerField(default=0, help_text='Number of audio chunks analyzed by the ML model.'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='content_deleted',
            field=models.BooleanField(default=False, help_text='True once full_transcript has been cleared.'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='user_confirmed_scam',
            field=models.BooleanField(blank=True, help_text='AI decides scam status. This is for user override only.', null=True),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['scam_detected_by_ai'], name='call_sessio_scam_de_48765f_idx'),
        ),
        migrations.DeleteModel(
            name='TranscriptChunk',
        ),
    ]
