# Generated by Django 4.2.10 on 2026-02-15 14:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberArchived',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_hash', models.CharField(db_index=True, help_text='SHA-256 hash of phone number (privacy-protected)', max_length=64, unique=True)),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('historical_peak_risk', models.IntegerField(default=0)),
                ('historical_report_count', models.IntegerField(default=0)),
                ('historical_scam_type', models.CharField(choices=[('kra_impersonation', 'KRA Impersonation'), ('mpesa_fraud', 'M-Pesa Fraud'), ('bank_impersonation', 'Bank Impersonation'), ('lottery_prize', 'Lottery/Prize Scam'), ('emergency_scam', 'Emergency Scam'), ('loan_scam', 'Loan Scam'), ('investment_scam', 'Investment Scam'), ('romance_scam', 'Romance Scam'), ('phishing', 'Phishing'), ('other', 'Other')], default='other', max_length=50)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_from_active_at', models.DateTimeField(blank=True, null=True)),
                ('days_in_active_db', models.IntegerField(default=0)),
                ('recovery_start_date', models.DateTimeField(blank=True, null=True)),
                ('normal_calls_since_archive', models.IntegerField(default=0)),
                ('reactivation_count', models.IntegerField(default=0)),
                ('last_reactivation_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archived Number',
                'verbose_name_plural': 'Archived Numbers',
                'db_table': 'phone_numbers_archived',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['phone_number_hash'], name='phone_numbe_phone_n_89598c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberActive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_hash', models.CharField(db_index=True, help_text='SHA-256 hash of phone number (privacy-protected)', max_length=64, unique=True)),
                ('risk_score', models.IntegerField(default=50, help_text='Risk score: 30-100 (HIGH: 70-100, MEDIUM: 30-69)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)])),
                ('primary_scam_type', models.CharField(choices=[('kra_impersonation', 'KRA Impersonation'), ('mpesa_fraud', 'M-Pesa Fraud'), ('bank_impersonation', 'Bank Impersonation'), ('lottery_prize', 'Lottery/Prize Scam'), ('emergency_scam', 'Emergency Scam'), ('loan_scam', 'Loan Scam'), ('investment_scam', 'Investment Scam'), ('romance_scam', 'Romance Scam'), ('phishing', 'Phishing'), ('other', 'Other')], default='other', max_length=50)),
                ('report_count', models.IntegerField(default=0)),
                ('verified_reports', models.IntegerField(default=0)),
                ('false_positive_count', models.IntegerField(default=0)),
                ('first_reported_at', models.DateTimeField(auto_now_add=True)),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
                ('last_incident_at', models.DateTimeField(blank=True, null=True)),
                ('last_decay_calculated', models.DateTimeField(auto_now=True)),
                ('decay_factor', models.FloatField(default=1.0)),
                ('total_victims_estimated', models.IntegerField(default=0)),
                ('total_amount_lost_estimated', models.DecimalField(decimal_places=2, default=0, help_text='Estimated total amount lost in KES', max_digits=12)),
                ('regions_reported', models.JSONField(blank=True, default=list, help_text='List of regions where this number was reported (no PII)')),
                ('eligible_for_archive', models.BooleanField(default=False)),
                ('days_since_last_incident', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Active Scam Number',
                'verbose_name_plural': 'Active Scam Numbers',
                'db_table': 'phone_numbers_active',
                'ordering': ['-risk_score', '-last_reported_at'],
                'indexes': [models.Index(fields=['risk_score', '-last_reported_at'], name='phone_numbe_risk_sc_42b52a_idx'), models.Index(fields=['phone_number_hash'], name='phone_numbe_phone_n_7307c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScamIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_hash', models.CharField(db_index=True, help_text='SHA-256 hash of reported phone number', max_length=64)),
                ('scam_type', models.CharField(choices=[('kra_impersonation', 'KRA Impersonation'), ('mpesa_fraud', 'M-Pesa Fraud'), ('bank_impersonation', 'Bank Impersonation'), ('lottery_prize', 'Lottery/Prize Scam'), ('emergency_scam', 'Emergency Scam'), ('loan_scam', 'Loan Scam'), ('investment_scam', 'Investment Scam'), ('romance_scam', 'Romance Scam'), ('phishing', 'Phishing'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.IntegerField(default=50, help_text='Severity score: 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source', models.CharField(choices=[('user_report', 'User Report'), ('ai_detection', 'AI Detection'), ('manual_review', 'Manual Review')], default='user_report', max_length=20)),
                ('has_recording', models.BooleanField(default=False)),
                ('has_transcript', models.BooleanField(default=False)),
                ('evidence_quality', models.CharField(choices=[('none', 'No Evidence'), ('low', 'Low Quality'), ('medium', 'Medium Quality'), ('high', 'High Quality')], default='none', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by_ai', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('incident_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('victim_lost_money', models.BooleanField(default=False)),
                ('amount_lost', models.DecimalField(blank=True, decimal_places=2, help_text='Amount lost in KES', max_digits=10, null=True)),
                ('region', models.CharField(blank=True, help_text='County/region (anonymized, no specific location)', max_length=100)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scam Incident',
                'verbose_name_plural': 'Scam Incidents',
                'db_table': 'scam_incidents',
                'ordering': ['-incident_datetime'],
                'indexes': [models.Index(fields=['phone_number_hash', '-incident_datetime'], name='scam_incide_phone_n_2b52fc_idx'), models.Index(fields=['scam_type', '-incident_datetime'], name='scam_incide_scam_ty_3ab506_idx'), models.Index(fields=['reported_by', '-incident_datetime'], name='scam_incide_reporte_fd088a_idx')],
            },
        ),
    ]
