# Generated by Django 4.2.10 on 2026-02-15 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scam_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterCredibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.IntegerField(default=0)),
                ('verified_reports', models.IntegerField(default=0)),
                ('false_reports', models.IntegerField(default=0)),
                ('pending_reports', models.IntegerField(default=0)),
                ('credibility_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('credibility_tier', models.CharField(choices=[('new', 'New Reporter'), ('bronze', 'Bronze Reporter'), ('silver', 'Silver Reporter'), ('gold', 'Gold Reporter'), ('flagged', 'Flagged Suspicious')], default='new', max_length=20)),
                ('first_report_at', models.DateTimeField(auto_now_add=True)),
                ('last_report_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporter Credibility',
                'verbose_name_plural': 'Reporter Credibilities',
                'db_table': 'reporter_credibility',
            },
        ),
        migrations.CreateModel(
            name='ScamEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('narrative', models.TextField(blank=True, help_text='Detailed description of what happened (min 50 chars)')),
                ('narrative_language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('audio_file', models.FileField(blank=True, help_text='Call recording (voice-anonymized)', null=True, upload_to='evidence/audio/%Y/%m/%d/')),
                ('audio_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('audio_anonymized', models.BooleanField(default=False)),
                ('transcript', models.TextField(blank=True, help_text='Conversation transcript (PII redacted)')),
                ('transcript_source', models.CharField(choices=[('user_typed', 'User Typed'), ('auto_generated', 'Auto-Generated')], default='user_typed', max_length=20)),
                ('transcript_pii_redacted', models.BooleanField(default=False)),
                ('screenshot_1', models.ImageField(blank=True, null=True, upload_to='evidence/screenshots/%Y/%m/%d/')),
                ('screenshot_2', models.ImageField(blank=True, null=True, upload_to='evidence/screenshots/%Y/%m/%d/')),
                ('screenshot_3', models.ImageField(blank=True, null=True, upload_to='evidence/screenshots/%Y/%m/%d/')),
                ('call_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('user_confidence_level', models.IntegerField(default=5, help_text="User's confidence this is a scam (1-10)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('verified_by_moderator', models.BooleanField(default=False)),
                ('moderator_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user_consented_storage', models.BooleanField(default=False, help_text='User consented to storing this evidence')),
                ('user_consented_training', models.BooleanField(default=False, help_text='User consented to using for ML training')),
                ('auto_delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scam Evidence',
                'verbose_name_plural': 'Scam Evidence',
                'db_table': 'scam_evidence',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='scamincident',
            name='scam_incide_reporte_fd088a_idx',
        ),
        migrations.AlterField(
            model_name='phonenumberactive',
            name='regions_reported',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scamincident',
            name='amount_lost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scamincident',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scamevidence',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='scam_database.scamincident'),
        ),
        migrations.AddField(
            model_name='reportercredibility',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_credibility', to=settings.AUTH_USER_MODEL),
        ),
    ]
