# Generated by Django 4.2.10 on 2026-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Phone number in international format (+254...)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_hash',
            field=models.CharField(help_text='SHA-256 hash of phone number for privacy', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_verified'], name='otp_verific_phone_n_e44aa5_idx'), models.Index(fields=['created_at'], name='otp_verific_created_6264a2_idx')],
            },
        ),
    ]
